config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "user"}

  devise_scope :user do
    get 'user/:id' => 'user#show', as: :user_profile
  end

  root controller: :videos, action: :index



  get "/pages/login" => "users#login", as: :login
  get "/pages/signup" => "users#signup", as: :signup
  get "/pages/:page" => "pages#page", as: :page
  get "/pages/pageindex" => "pages#pageindex", as: :pageindex

  resources :videos
  resources :comedians
  resources :publishers
  resources :categories
  resources :profiles

  # resources :user, only: [:show]

end

app/models/comedian.rb
class Comedian < ApplicationRecord

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  has_many :videos
  validates_presence_of  :name

  def self.options_for_select
    order('LOWER(name)').map { |e| [e.name, e.id]}
  end

end

app/controllers/comedians_controller.rb
class ComediansController < ApplicationController
  load_and_authorize_resource param_method: :comedian_param, find_by: :slug
  skip_authorize_resource only: :index

  def index
    @comedians = Comedian.all
  end

  def new
    @comedian = Comedian.new
  end

  def create
    @comedian = Comedian.new(comedian_param)
    if @comedian.save
      flash[:notice] = 'Comedian successfully added'
      redirect_to request.referrer
    else
      flash[:notice]= "Sorry! You must enter a name"
      redirect_to new_comedian_path
    end
  end

  def edit
    @comedian = Comedian.friendly.find(params[:id])
  end

  def update
    @comedian = Comedian.friendly.find(params[:id])
    if @comedian.update_attributes(comedian_param)
      redirect_to  comedians_path
      flash[:notice] = "Comedian's record successfully updated"
    else
      render 'edit'
    end
  end


  def comedian_param
    params.require(:comedian)
          .permit(:name)
  end

end

app/views/comedians/_list.html.haml
.box-body.table-responsive.no-padding
  %table.table.table-hover
    %tr
      %th Comedian Name
      %th Date Added
      %th
      %th
      %th
    - @comedians.each do |comedian|
      %tr
        %td #{comedian.name}
        - @date = comedian.created_at
        %td
          %span.label.label-info #{@date.strftime('%B, %Y')}
        %td
          = link_to "Show", comedian_path(comedian), class:"label label-success "
        %td
          = link_to "Edit", edit_comedian_path(comedian), class:"label label-success "

app/views/comedians/edit.html.haml
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      Edit Comedian
      %small Edit Comedian
    %ol.breadcrumb
      %li
        %a{:href => "#"}
          %i.fa.fa-dashboard
          Home
      %li
        %a{:href => "#"} Edit Comedian
      %li.active Edit Comedian

  / Main content
  %section.content
    .row
      / left column
      .col-md-6
        / general form elements
        .box.box-primary{"data-aos" => "fade-up"}
          .box-header.with-border
            %h3.box-title Edit Comedian
          .box-body
            = form_for @comedian do |f|
              - if @comedian.errors.any?
                - @comedian.errors.full_messages.each do |message|
                  = message
              .form-group
                = f.label :name, "Comedian's Name"
                %br
                = f.text_field  :name, class: "form-control", :placeholder => "Enter Comedian full name"
                %br
                = f.submit 'Submit', class: "btn btn-primary"
            = flash[:notice]

app/views/comedians/index.html.haml
- content_for :before_scripts do
  %link{:href => "/plugins/jvectormap/jquery-jvectormap-1.2.2.css", :rel => "stylesheet"}

.content-wrapper.dashboard-page
  %section.content-header
    .row
      .col-sm-6.col-xs-12
        %h1.page-title
          All Comedians
        %ol.breadcrumb
          %li
            %a{:href => "#"}
              %i.fa.fa-dashboard
              Home
          %li.active Comedians

  %section.content
    = flash[:notice]
    .row
      .col-xs-12
        .box{"data-aos" => "fade-up"}
          .box-header
            %h3.box-title COMEDIANS
            .box-tools
              -#.input-group{:style => "width: 150px;"}
              -#  = form_for videos_path, method: 'get' do |f|
              -#    = f.text_field :search,  placeholder: "Search Video", class: "form-control.input-sm.pull-right"
              -#    -#.input-group-btn
              -#    -#  %button.btn.btn-sm.btn-default
              -#    -#    %i.fa.fa-search

              / /.box-headerx

          = render( partial: 'comedians/list')

- content_for :after_body do
  %script{:src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyDjmOKmkLPUWeJLc9P9L-H-ZynmHl16Lhs"}
  %script{:src => "/plugins/sparkline/jquery.sparkline.min.js"}
  %script{:src => "/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"}
  %script{:src => "/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"}
  %script{:src => "/plugins/chartjs-2/Chart.min.js"}
  %script{:src => "/assets/pages/dashboard.js"}

app/views/comedians/new.html.haml
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      Add New Comedian
      %small New Comedians
    %ol.breadcrumb
      %li
        %a{:href => "#"}
          %i.fa.fa-dashboard
          Home
      %li
        %a{:href => "#"} Add Comedian
      %li.active New Comedian

  / Main content
  %section.content
    .row
      / left column
      .col-md-6
        / general form elements
        .box.box-primary{"data-aos" => "fade-up"}
          .box-header.with-border
            %h3.box-title New Comedian
          .box-body
            = form_for @comedian do |f|
              - if @comedian.errors.any?
                - @comedian.errors.full_messages.each do |message|
                  = message
              .form-group
                = f.label :name, "Comedian's Name"
                %br
                = f.text_field  :name, class: "form-control", :placeholder => "Enter Comedian full name"
                %br
                = f.submit 'Submit', class: "btn btn-primary"
            = flash[:notice]