config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "user"}

  devise_scope :user do
    get 'user/:id' => 'user#show', as: :user_profile
  end

  root controller: :videos, action: :index



  get "/pages/login" => "users#login", as: :login
  get "/pages/signup" => "users#signup", as: :signup
  get "/pages/:page" => "pages#page", as: :page
  get "/pages/pageindex" => "pages#pageindex", as: :pageindex

  resources :videos
  resources :comedians
  resources :publishers
  resources :categories
  resources :profiles

  # resources :user, only: [:show]

end

app/views/shared/_customization_modal.html.haml
#toggle-customization-modal
  %button.btn.btn-default.btn-sm{"data-target" => "#customizationModal", "data-toggle" => "modal"}
    %i.fa.fa-gears
#customizationModal.modal.fade{:role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4.modal-title Customize Atlas Template
      .modal-body
        %h5 Choose a color scheme
        %ul.color-scheme-picker
          %li.color-scheme-box.pale-green{"data-color" => "skin-pale-green"}
          %li.color-scheme-box.deep-blue{"data-color" => "skin-deep-blue"}
          %li.color-scheme-box.deep-orange{"data-color" => "skin-deep-orange"}
          %li.color-scheme-box.deep-purple{"data-color" => "skin-deep-purple"}
          %li.color-scheme-box.blue-grey{"data-color" => "skin-blue-grey"}
        %hr/
        %h5 Choose a sidebar image
        %ul.sidebar-image-picker
          %li.sidebar-image-box{"data-image" => "dark-waves"}
            = image_tag "sidebar-thumbs/dark-waves.jpg", class: "img-responsive"
          %li.sidebar-image-box{"data-image" => "starry"}
            = image_tag "sidebar-thumbs/starry.jpg", class: "img-responsive"
          %li.sidebar-image-box{"data-image" => "misty-mountains"}
            = image_tag "sidebar-thumbs/misty-mountains.jpg", class: "img-responsive"
          %li.sidebar-image-box{"data-image" => "sunrise"}
            = image_tag "sidebar-thumbs/sunrise.jpg", class: "img-responsive"
          %li.sidebar-image-box{"data-image" => "rocky-beach"}
            = image_tag "sidebar-thumbs/rocky-beach.jpg", class: "img-responsive"
          %li.sidebar-image-box{"data-image" => "starry-mountains"}
            = image_tag "sidebar-thumbs/starry-mountains.jpg", class: "img-responsive"
    / /.modal-content
  / /.modal-dialog
/ /.modal

app/views/shared/_footer.html.haml
%footer.main-footer
  .pull-right.hidden-xs
    by
    %strong EFLUXZ MOBILE
  %strong
    Copyright © 2017
    = succeed "." do
      %a{:href => "http://laffhub.com"} LAFFHUB CONTENT
  All rights reserved.

app/views/shared/_header.html.haml
%body
  %header.main-header
    %a.logo{:href => "/index.html"}
      %span.logo-lg LAFFHUB CATALOGUE
    %nav.navbar.navbar-static-top{:role => "navigation"}
      %a.sidebar-toggle.border-right.border-left{"data-toggle" => "offcanvas", :href => "#", :role => "button"}
        %span.sr-only Toggle navigation
      .navbar-custom-menu
        %ul.nav.navbar-nav
          %li.dropdown.notifications-menu
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              %i.fa.fa-bell-o
              %span.label.label-warning 10
            %ul.dropdown-menu
              %li.header You have 10 notifications
              %li
                %ul.menu
                  %li
                    %a{:href => "#"}
                      %i.fa.fa-users.text-aqua
                      5 new members joined today
                  %li
                    %a{:href => "#"}
                      %i.fa.fa-warning.text-yellow
                      Very long description here that may not fit into the page and may cause design problems
                  %li
                    %a{:href => "#"}
                      %i.fa.fa-users.text-red
                      5 new members joined
                  %li
                    %a{:href => "#"}
                      %i.fa.fa-shopping-cart.text-green
                      25 sales made
                  %li
                    %a{:href => "#"}
                      %i.fa.fa-user.text-red
                      You changed your username
              %li.footer
                %a{:href => "#"} View all
          %li.dropdown.user.user-menu
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              %span.hidden-xs
              - if user_signed_in? && current_user
                = "#{current_user.first_name} #{current_user.last_name}"
            %ul.dropdown-menu
              %li.user-header
                %p
                  #{current_user.first_name} #{current_user.last_name}
                  %small
                    - @date = current_user.created_at
                    Member since #{@date.strftime('%B, %Y')}
              %li.user-footer
                .pull-left
                  =link_to "My Profile", user_profile_path(current_user), class:"btn btn-default btn-flat"
                .pull-right
                  = link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-default btn-flat"

app/views/shared/_header_meta.html.haml
%meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
%meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0", :name => "viewport"}/
%meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
%meta{:content => "black-translucent", :name => "apple-mobile-web-app-status-bar-style"}/
%link{:href => "/images/icons/apple-touch-icon-57x57.png", :rel => "apple-touch-icon", :sizes => "57x57"}/
%link{:href => "/images/icons/apple-touch-icon-60x60.png", :rel => "apple-touch-icon", :sizes => "60x60"}/
%link{:href => "/images/icons/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
%link{:href => "/images/icons/apple-touch-icon-76x76.png", :rel => "apple-touch-icon", :sizes => "76x76"}/
%link{:href => "/images/icons/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/
%link{:href => "/images/icons/apple-touch-icon-120x120.png", :rel => "apple-touch-icon", :sizes => "120x120"}/
%link{:href => "/images/icons/apple-touch-icon-144x144.png", :rel => "apple-touch-icon", :sizes => "144x144"}/
%link{:href => "/images/icons/apple-touch-icon-152x152.png", :rel => "apple-touch-icon", :sizes => "152x152"}/
%link{:href => "/images/icons/apple-touch-icon-180x180.png", :rel => "apple-touch-icon", :sizes => "180x180"}/
%link{:href => "/images/icons/favicon-32x32.png", :rel => "icon", :sizes => "32x32", :type => "image/png"}/
%link{:href => "/images/icons/android-chrome-192x192.png", :rel => "icon", :sizes => "192x192", :type => "image/png"}/
%link{:href => "/images/icons/favicon-96x96.png", :rel => "icon", :sizes => "96x96", :type => "image/png"}/
%link{:href => "/images/icons/favicon-16x16.png", :rel => "icon", :sizes => "16x16", :type => "image/png"}/
%link{:href => "/images/icons/manifest.json", :rel => "manifest"}/
%link{:color => "#5bbad5", :href => "/images/icons/safari-pinned-tab.svg", :rel => "mask-icon"}/
%meta{:content => "#da532c", :name => "msapplication-TileColor"}/
%meta{:content => "/mstile-144x144.png", :name => "msapplication-TileImage"}/
%meta{:content => "#ffffff", :name => "theme-color"}/
/ SEARCH
%meta{:content => "", :name => "author"}/
%meta{:content => "", :name => "description"}/
%link{:href => "", :rel => "canonical"}/
/ TWITTER
%meta{:content => "", :name => "twitter:card"}/
%meta{:content => "", :name => "twitter:site"}/
%meta{:content => "", :name => "twitter:creator"}/
%meta{:content => "", :name => "twitter:title"}/
%meta{:content => "", :name => "twitter:description"}/
%meta{:content => "", :name => "twitter:image:src"}/
/ FACEBOOK
%meta{:content => "", :property => "og:site_name"}/
%meta{:content => "", :property => "og:url"}/
%meta{:content => "", :property => "og:type"}/
%meta{:content => "", :property => "og:title"}/
%meta{:content => "", :property => "og:description"}/
%meta{:content => "", :property => "og:image"}/
%meta{:content => "", :property => "fb:app_id"}/
%meta{:content => "", :property => "fb:admins"}/
/ G+
%meta{:content => "", :itemprop => "name"}/
%meta{:content => "", :itemprop => "description"}/
%meta{:content => "", :itemprop => "image"}/

app/views/shared/_sidebar.html.haml
%aside.main-sidebar
  %section.sidebar
    .user-panel
      %ul.sidebar-menu
        %li.header MAIN NAVIGATION
        %li
          = link_to root_path, data: { pjax: true} do
            %i.fa.fa-circle-o
            %span Dashboard
        %li.header GENERAL PAGES

        %li.treeview
          %a{:href => "#"}
            %i.fa.fa-group
            %span Comedians
            %i.fa.fa-angle-left.pull-right
          %ul.treeview-menu
            %li
              = link_to comedians_path, data: { pjax: true} do
                %i.fa.fa-plus-circle
                %span View Comedians

            %li
              = link_to new_comedian_path, data: { pjax: true} do
                %i.fa.fa-plus-circle
                %span Add Comedian

        %li.treeview
          %a{:href => "#"}
            %i.fa.fa-video-camera
            %span Publishers
            %i.fa.fa-angle-left.pull-right
          %ul.treeview-menu
            %li
              = link_to publishers_path, data: { pjax: true} do
                %i.fa.fa-plus-circle
                %span View Publishers

            %li
              = link_to new_publisher_path, data: { pjax: true} do
                %i.fa.fa-plus-circle
                %span Add Publisher

        %li.treeview
          %a{:href => "#"}
            %i.fa.fa-file-movie-o
            %span Category
            %i.fa.fa-angle-left.pull-right
          %ul.treeview-menu
            %li
              = link_to categories_path, data: { pjax: true} do
                %i.fa.fa-plus-circle
                %span View Categories

            %li
              = link_to new_category_path, data: { pjax: true} do
                %i.fa.fa-plus-circle
                %span Add Category

        %li.treeview
          %a{:href => '#'}
            %i.fa.fa.fa-video-camera
            %span Video
            %i.fa.fa-angle-left.pull-right
          %ul.treeview-menu
            %li
              = link_to videos_path, data: { pjax: true} do
                %i.fa.fa-plus-circle
                %span View Videos
            %li
              = link_to new_video_path, data: { pjax: true} do
                %i.fa.fa-plus-circle
                %span Add Video

        %li.treeview
          %a{:href => "#"}
            %i.fa.fa.fa-male
            %span Users
            %i.fa.fa-angle-left.pull-right
          %ul.treeview-menu
            %li
              = link_to new_user_registration_path, data: { pjax: true} do
                %i.fa.fa-plus-circle
                %span Create User

        %li.treeview
          %a{:href => "#"}
            %i.fa.fa-laptop
            %span UI Elements
            %i.fa.fa-angle-left.pull-right
          %ul.treeview-menu
            %li
              = link_to page_path(page: "ui_basic"), data: { pjax: true} do
                %i.fa.fa-asterisk
                General
            %li
              = link_to page_path(page: "icons"), data: { pjax: true} do
                %i.fa.fa-fonticons
                Icons
            %li
              = link_to page_path(page: "buttons"), data: { pjax: true} do
                %i.fa.fa-hand-pointer-o
                Buttons
            %li
              = link_to page_path(page: "slider"), data: { pjax: true} do
                %i.fa.fa-sliders
                Sliders  Toggles
            %li
              = link_to page_path(page: "timeline"), data: { pjax: true} do
                %i.fa.fa-clock-o
                Timeline
            %li
              = link_to page_path(page: "modals"), data: { pjax: true} do
                %i.fa.fa-bullhorn
                Modals
        %li.treeview
          %a{:href => "#"}
            %i.fa.fa-edit
            %span Forms
            %i.fa.fa-angle-left.pull-right
          %ul.treeview-menu
            %li
              = link_to page_path(page: "forms_simple"), data: { pjax: true} do
                %i.fa.fa-keyboard-o
                General Elements
        %li.treeview
          %a{:href => "#"}
            %i.fa.fa-table
            %span Tables
            %i.fa.fa-angle-left.pull-right
          %ul.treeview-menu
            %li
              = link_to page_path(page: "tables_simple"), data: { pjax: true} do
                %i.fa.fa-table
                Simple tables
            %li
              = link_to page_path(page: "tables_data"), data: { pjax: true} do
                %i.fa.fa-list-alt
                Data tables
        %li.treeview
          %a{:href => "#"}
            %i.fa.fa-folder
            %span Custom Pages
            %i.fa.fa-angle-left.pull-right
          %ul.treeview-menu
            %li
              = link_to page_path(page: "404"), data: { pjax: true} do
                %i.fa.fa-exclamation-circle
                404 Error
            %li
              = link_to page_path(page: "500"), data: { pjax: true} do
                %i.fa.fa-exclamation-triangle
                500 Error