config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "user"}

  devise_scope :user do
    get 'user/:id' => 'user#show', as: :user_profile
  end

  root controller: :videos, action: :index



  get "/pages/login" => "users#login", as: :login
  get "/pages/signup" => "users#signup", as: :signup
  get "/pages/:page" => "pages#page", as: :page
  get "/pages/pageindex" => "pages#pageindex", as: :pageindex

  resources :videos
  resources :comedians
  resources :publishers
  resources :categories
  resources :profiles

  # resources :user, only: [:show]

end

app/models/publisher.rb
class Publisher < ApplicationRecord

  extend FriendlyId
  friendly_id :publisher_name, use: [:slugged, :history]

  has_many :videos
  validates_presence_of :publisher_name

  def self.options_for_select
    order('LOWER(publisher_name)').map { |e| [e.publisher_name, e.id]}
  end

end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  load_and_authorize_resource param_method: :publisher_param, find_by: :slug
  skip_authorize_resource only: :index

  def index
    @publishers = Publisher.all
  end

  def new
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_param)
    if @publisher.save
      flash[:notice] = 'Publisher successfully added'
      redirect_to new_publisher_path
    else
      render new
    end
  end

  def edit
    @publisher = Publisher.friendly.find(params[:id])
  end

  def update
      @publisher = Publisher.friendly.find(params[:id])
      if @pubisher.update_attributes(publisher_param)
        redirect_to  publishers_path
        flash[:notice] = "Publisher's record successfully updated"
      else
        render 'edit'
      end
  end


  private

  def publisher_param
    params.require(:publisher)
        .permit(:publisher_name)
  end
end

app/views/publishers/_list.html.haml
.box-body.table-responsive.no-padding
  %table.table.table-hover
    %tr
      %th Publisher Name
      %th Date Created
      %th
      %th
      %th
    - @publishers.each do |publisher|
      %tr
        %td #{publisher.publisher_name}
        - @date = publisher.created_at
        %td
          %span.label.label-info #{@date.strftime('%B, %Y')}
        %td
          = link_to "Show", publisher_path(publisher), class:"label label-success "
        %td
          = link_to "Edit", edit_publisher_path(publisher), class:"label label-success "

app/views/publishers/edit.html.haml
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      Edit Publisher Form
      %small Edit Publisher
    %ol.breadcrumb
      %li
        %a{:href => "#"}
          %i.fa.fa-dashboard
          Home
      %li
        %a{:href => "#"} Edit Publisher
      %li.active Edit Publisher
  / Main content
  %section.content
    .row
      / left column
      .col-md-6
        / general form elements
        .box.box-primary{"data-aos" => "fade-up"}
          .box-header.with-border
            %h3.box-title Edit Publisher
          .box-body
            = form_for @publisher do |f|
              .form-group
                = f.label :publisher_name, "Publisher's Name"
                %br
                = f.text_field  :publisher_name, class: "form-control", :placeholder => "Enter Publisher's full name"
                %br
                = f.submit 'Submit', class: "btn btn-primary"
            = flash[:notice]

app/views/publishers/index.html.haml
- content_for :before_scripts do
  %link{:href => "/plugins/jvectormap/jquery-jvectormap-1.2.2.css", :rel => "stylesheet"}

.content-wrapper.dashboard-page
  %section.content-header
    .row
      .col-sm-6.col-xs-12
        %h1.page-title
          All Publishers
        %ol.breadcrumb
          %li
            %a{:href => "#"}
              %i.fa.fa-dashboard
              Home
          %li.active Publishers

  %section.content
    = flash[:notice]
    .row
      .col-xs-12
        .box{"data-aos" => "fade-up"}
          .box-header
            %h3.box-title PUBLISHERS
            .box-tools
              -#.input-group{:style => "width: 150px;"}
              -#  = form_for videos_path, method: 'get' do |f|
              -#    = f.text_field :search,  placeholder: "Search Video", class: "form-control.input-sm.pull-right"
              -#    -#.input-group-btn
              -#    -#  %button.btn.btn-sm.btn-default
              -#    -#    %i.fa.fa-search

              / /.box-headerx

          = render( partial: 'publishers/list')

- content_for :after_body do
  %script{:src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyDjmOKmkLPUWeJLc9P9L-H-ZynmHl16Lhs"}
  %script{:src => "/plugins/sparkline/jquery.sparkline.min.js"}
  %script{:src => "/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"}
  %script{:src => "/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"}
  %script{:src => "/plugins/chartjs-2/Chart.min.js"}
  %script{:src => "/assets/pages/dashboard.js"}



= flash[:notice]

app/views/publishers/new.html.haml
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      Add Publisher
      %small New Publisher
    %ol.breadcrumb
      %li
        %a{:href => "#"}
          %i.fa.fa-dashboard
          Home
      %li
        %a{:href => "#"} Add Publisher
      %li.active New Publisher
  / Main content
  %section.content
    .row
      / left column
      .col-md-6
        / general form elements
        .box.box-primary{"data-aos" => "fade-up"}
          .box-header.with-border
            %h3.box-title New Publisher
          .box-body
            = form_for @publisher do |f|
              .form-group
                = f.label :publisher_name, "Publisher's Name"
                %br
                = f.text_field  :publisher_name, class: "form-control", :placeholder => "Enter Publisher's full name"
                %br
                = f.submit 'Submit', class: "btn btn-primary"
            = flash[:notice]